apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base/namespace.yaml
  - ../../app/services.yaml
  - ../../app/istio.yaml
  - ../../app/rollout.yaml
  - ../../app/analysis/success-rate.yaml
  - ../../app/analysis/latency-p95.yaml

patches:
  - path: patches.yaml