apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - ../../app

patches:
  - target:
      kind: Rollout
      name: webapp
    path: patches.yaml